//
// File generated by HDevelop for HALCON/.NET (C#) Version 24.05.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_GrayImage, ho_Region;
    HObject ho_ConnectedRegions, ho_SelectedRegion, ho_RegionFillUp;
    HObject ho_RegionOpening, ho_RegionTrans, ho_ImageReduced;
    HObject ho_RegionAffineTrans, ho_ImageAffineTrans, ho_ImageReduced1;

    // Local control variables 

    HTuple hv_Area = new HTuple(), hv_Row = new HTuple();
    HTuple hv_Column = new HTuple(), hv_Phi = new HTuple();
    HTuple hv_HomMat2D = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_GrayImage);
    HOperatorSet.GenEmptyObj(out ho_Region);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_SelectedRegion);
    HOperatorSet.GenEmptyObj(out ho_RegionFillUp);
    HOperatorSet.GenEmptyObj(out ho_RegionOpening);
    HOperatorSet.GenEmptyObj(out ho_RegionTrans);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_RegionAffineTrans);
    HOperatorSet.GenEmptyObj(out ho_ImageAffineTrans);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced1);
    //Image Acquisition 01: Code generated by Image Acquisition 01
    ho_Image.Dispose();
    HOperatorSet.ReadImage(out ho_Image, "E:/上位机/R003-2025年3月录制，Halcon联合C#编程，从零手写《图像处理实战》-39P-VIP/000-课件源码+PDF文档/000-课件源码+PDF文档/Code/汽车.jpg");
    //灰度化
    ho_GrayImage.Dispose();
    HOperatorSet.Rgb1ToGray(ho_Image, out ho_GrayImage);
    //二值化分割
    ho_Region.Dispose();
    HOperatorSet.Threshold(ho_GrayImage, out ho_Region, 0, 66);
    //区域分离
    ho_ConnectedRegions.Dispose();
    HOperatorSet.Connection(ho_Region, out ho_ConnectedRegions);
    //ROI
    ho_SelectedRegion.Dispose();
    HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegion, "area", 
        "and", 341000, 341600);
    //形态学处理：填充，去毛刺,转换
    ho_RegionFillUp.Dispose();
    HOperatorSet.FillUp(ho_SelectedRegion, out ho_RegionFillUp);
    ho_RegionOpening.Dispose();
    HOperatorSet.OpeningCircle(ho_RegionFillUp, out ho_RegionOpening, 3);
    ho_RegionTrans.Dispose();
    HOperatorSet.ShapeTrans(ho_RegionOpening, out ho_RegionTrans, "rectangle2");
    //锁定区域
    ho_ImageReduced.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_RegionOpening, out ho_ImageReduced);

    //构建仿射变换:获取坐标和角度-> 矩阵
    hv_Area.Dispose();hv_Row.Dispose();hv_Column.Dispose();
    HOperatorSet.AreaCenter(ho_RegionOpening, out hv_Area, out hv_Row, out hv_Column);
    hv_Phi.Dispose();
    HOperatorSet.OrientationRegion(ho_RegionOpening, out hv_Phi);
    //创建矩阵
    hv_HomMat2D.Dispose();
    HOperatorSet.HomMat2dIdentity(out hv_HomMat2D);
    //创建扶正矩阵
    hv_HomMat2D.Dispose();
    HOperatorSet.VectorAngleToRigid(hv_Row, hv_Column, hv_Phi, hv_Row, hv_Column, 
        0, out hv_HomMat2D);
    //区域扶正
    ho_RegionAffineTrans.Dispose();
    HOperatorSet.AffineTransRegion(ho_RegionOpening, out ho_RegionAffineTrans, hv_HomMat2D, 
        "nearest_neighbor");
    //原图扶正
    ho_ImageAffineTrans.Dispose();
    HOperatorSet.AffineTransImage(ho_ImageReduced, out ho_ImageAffineTrans, hv_HomMat2D, 
        "constant", "false");

    //锁定车牌
    ho_ImageReduced1.Dispose();
    HOperatorSet.ReduceDomain(ho_ImageAffineTrans, ho_RegionAffineTrans, out ho_ImageReduced1
        );
    ho_Image.Dispose();
    ho_GrayImage.Dispose();
    ho_Region.Dispose();
    ho_ConnectedRegions.Dispose();
    ho_SelectedRegion.Dispose();
    ho_RegionFillUp.Dispose();
    ho_RegionOpening.Dispose();
    ho_RegionTrans.Dispose();
    ho_ImageReduced.Dispose();
    ho_RegionAffineTrans.Dispose();
    ho_ImageAffineTrans.Dispose();
    ho_ImageReduced1.Dispose();

    hv_Area.Dispose();
    hv_Row.Dispose();
    hv_Column.Dispose();
    hv_Phi.Dispose();
    hv_HomMat2D.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

